server.modules = (
  "mod_access",
  "mod_cgi"
)

server.document-root = "/jffs/addons/mihomo/webui/www"
server.bind = "0.0.0.0"
server.port = 5581
server.pid-file = "/opt/root/mihomo/run/mihomo-web.pid"
server.username = "nobody"
server.groupname = "nobody"
index-file.names = ( "index.html" )

$HTTP["url"] =~ "^/server\.conf$" {
    url.access-deny = ( "" )
}

$HTTP["url"] =~ "^/cgi-bin/" {
    cgi.assign = ( "" => "/bin/sh" )
}
